# Generated by Django 3.0.1 on 2019-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('slug', models.TextField()),
                ('stock', models.CharField(max_length=100)),
                ('labels', models.CharField(max_length=100)),
            ],
        ),
    ]
