# Generated by Django 3.0.1 on 2020-01-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('rank', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), (' ', 'Default')], max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('rank', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), (' ', 'Default')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uppertext', models.CharField(max_length=300)),
                ('middletext', models.CharField(max_length=300)),
                ('lowertext', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new', 'new'), ('hot', 'hot'), ('inactive', 'inactive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.CharField(blank=True, choices=[('In Stock', 'In'), ('Out of Stock', 'Out')], max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
    ]
