# Generated by Django 3.0.1 on 2020-02-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200124_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubCategory',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.SubCategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=100),
        ),
    ]
