# Generated by Django 3.0.1 on 2020-02-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200202_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categorys',
        ),
    ]
