# Generated by Django 3.0.1 on 2020-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_item_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorys',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=100),
        ),
    ]
