# Generated by Django 3.0.1 on 2020-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categorys',
            field=models.CharField(choices=[('Food', 'Food'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Other', 'Other')], default=1, max_length=100),
        ),
    ]
