# Generated by Django 3.0.1 on 2020-02-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200202_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
